/* eslint-disable */
export const datajson = {
        code: -50797631,
        data: {
                records: [
                        {
                                analysisObject: "magna consequat in sit in",
                                assetType: "esse commodo voluptate qui",
                                chapter: [
                                        "occaecat consectetur velit"
                                ],
                                clientName: "qui ipsum",
                                content: { },
                                contractNo: "sit",
                                createTime: "2014-02-20T15:10:55.578Z",
                                createUserId: -85434891,
                                createUserName: "ullamco dolor et adipisicing laborum",
                                developerName: "commodo Excepteur aliqua ad velit",
                                doubt: 73668795,
                                downloadStatus: 93550789,
                                downloadUrl: "dolor in et laborum non",
                                generatorTime: "1965-04-24T10:46:20.236Z",
                                highVulnerability: 90680151,
                                hour: -12979233,
                                invalid: 31419782,
                                lastUpdateTime: "2002-04-12T20:54:34.914Z",
                                lowVulnerability: 82520464,
                                middleVulnerability: -55370430,
                                miss: -84640390,
                                projectId: 86610206,
                                proportion: "deserunt ipsum reprehenderit cillum",
                                putOn: -94608811,
                                reportId: 17769230,
                                reportName: "mollit offici",
                                reviewUserId: -19507853,
                                serviceSegment: "deserunt Excepteur dolor sint Duis",
                                status: -71850305,
                                submitTime: "1964-11-27T10:30:56.756Z",
                                targetIp: "dolor ut",
                                testAccount: "e",
                                testIp: "laborum consectetur",
                                type: -22412741,
                                valid: -88303711,
                                version: "ex anim",
                                webApplicationName: "mollit dolore deserunt minim ullamco",
                                webContainer: "quis Excepteur",
                                webContainerVersion: "magna fugiat ad "
                        },
                        {
                                analysisObject: "sint quis laborum elit",
                                assetType: "dolor officia dolore",
                                chapter: [
                                        "",
                                        "id amet voluptate",
                                        "quis consectetur dolore dolor Ut"
                                ],
                                clientName: "in proident labore occaecat",
                                content: { },
                                contractNo: "ipsum Lorem proident ex",
                                createTime: "1951-07-09T09:28:09.123Z",
                                createUserId: -76573615,
                                createUserName: "id ullamco Excepteur dolor",
                                developerName: "anim eiusmod aute consectetur amet",
                                doubt: -10344587,
                                downloadStatus: 77472872,
                                downloadUrl: "enim id",
                                generatorTime: "1977-11-11T09:51:15.357Z",
                                highVulnerability: -30082145,
                                hour: 90552176,
                                invalid: 85821948,
                                lastUpdateTime: "1944-02-01T22:55:55.248Z",
                                lowVulnerability: -27623837,
                                middleVulnerability: -87854320,
                                miss: 25037620,
                                projectId: 32587774,
                                proportion: "consectetur officia et velit ad",
                                putOn: 31611990,
                                reportId: -60543013,
                                reportName: "incididunt",
                                reviewUserId: -18111765,
                                serviceSegment: "deserunt dolor magna",
                                status: -72778682,
                                submitTime: "1992-01-15T15:16:26.256Z",
                                targetIp: "Duis dolor sit",
                                testAccount: "consequat deserunt nostrud dolore",
                                testIp: "cillum",
                                type: -96377490,
                                valid: -12011333,
                                version: "ea proident fugiat mollit do",
                                webApplicationName: "Ut dolor Duis ex",
                                webContainer: "adipisicing tempor in",
                                webContainerVersion: "nulla fugiat nostrud enim"
                        }
                ],
                total: -87722058
        },
        message: "do Excepteur ipsum sit"
}
