/* eslint-disable */
export const datajson = {
        code: -88899027.2140286,
        data: [
                {
                        clientName: 90543267.07466677,
                        sellerName: "mollit non dolor enim",
                        contractType: "sit",
                        keyword: "laborum ut ea",
                        level: "amet",
                        emergencyPerson: 65884435.64681712,
                        emergencyManager: "aute eu eiusmod",
                        happenTime: -43010771.95452252,
                        status: "laboris quis",
                        feedback: "laboris quis",
                },
                {
                        clientName: 90543267.07466677,
                        sellerName: "mollit non dolor enim",
                        contractType: "sit",
                        keyword: "laborum ut ea",
                        level: "amet",
                        emergencyPerson: 65884435.64681712,
                        emergencyManager: "aute eu eiusmod",
                        happenTime: -43010771.95452252,
                        status: "laboris quis",
                        feedback: "laboris quis",
                },
                {
                        clientName: 90543267.07466677,
                        sellerName: "mollit non dolor enim",
                        contractType: "sit",
                        keyword: "laborum ut ea",
                        level: "amet",
                        emergencyPerson: 65884435.64681712,
                        emergencyManager: "aute eu eiusmod",
                        happenTime: -43010771.95452252,
                        status: "laboris quis",
                        feedback: "laboris quis",
                },
                {
                        clientName: 90543267.07466677,
                        sellerName: "mollit non dolor enim",
                        contractType: "sit",
                        keyword: "laborum ut ea",
                        level: "amet",
                        emergencyPerson: 65884435.64681712,
                        emergencyManager: "aute eu eiusmod",
                        happenTime: -43010771.95452252,
                        status: "laboris quis",
                        feedback: "laboris quis",
                },
                {
                        clientName: 90543267.07466677,
                        sellerName: "mollit non dolor enim",
                        contractType: "sit",
                        keyword: "laborum ut ea",
                        level: "amet",
                        emergencyPerson: 65884435.64681712,
                        emergencyManager: "aute eu eiusmod",
                        happenTime: -43010771.95452252,
                        status: "laboris quis",
                        feedback: "laboris quis",
                },
        ],
        message: "pariatur"
}
