/* eslint-disable */
export const userinfojson = {
    code: 200,
    data: {
        user: {
            id: 15,
            account: '1',
            name: '1',
            img: '',
            phone: '1',
            email: '',
            status: 0,
            lastLoginTime: '2020-11-04 16:18:14',
            expired: 1,
            chPinyin: 'gaofan'
        },
        'permission': ['console_analysis_manager', 'outsourcing_manager', 'evil_ip_list', 'csovsTrial', 'protectNetDailySupportExport', 'code_review_list', 'csovself_resources', 'threat_expert', 'warn_analysis', 'log_analysis', 'event_list', 'ProjectManagement', 'secure_penetrate_report', 'csovself_professional_vul', 'epidemicVolunteer', 'daily_statistic', 'csovself_operation', 'console_hw_daily_project', 'sale_intelligence_evil_ip', 'emergency_report', 'vulManagent', 'dashboad', 'csovself_cloud', 'protectNetVolunteer', 'csovself_equipment', 'protectNetDailySupport', 'isrc_list', 'label_manage', 'emergenct_engineer_list', 'console_visual_analysis_demo', 'secure_penetrate_create', 'emergency_manager_list', 'console_hw_daily_own', 'epidemic', 'outsourcing_workload', 'SecureConfiguration', 'csovself_hw_before', 'rainbow', 'console_hw_daily', 'codeReview', 'epidemicVolunteerExport', 'console_schedule_manager', 'project_manager_workload', 'event_analysis', 'csovself', 'epidemicDailySupportExport', 'threat_engineer', 'threat_list', 'epidemicDailySupport', 'operate_response_engineer', 'csovapp_sitemap', 'secure_scan_report', 'console_happening_manager', 'csovself_professional', 'csovself_intelligent', 'emergency_case_review', 'console_intelligence_sales', 'console_hw_daily_report', 'csovsTrial_free', 'console_intelligence_manager', 'protectNet', 'csovapp_intelligence', 'WorkingDesk', 'UserManage', 'protectNetVolunteerExport', 'emergency_synchronized', 'csovself_app', 'secure_configuration_report', 'sale_intelligence', 'csovself_hw', 'staff_schedule', 'person_schedule', 'work_plan', 'console_incident_response', 'emergency_case', 'work_plan_list', 'RoleManage', 'threat_hot', 'SecureScan', 'ScanManagement', 'operate_response_manager', 'console_system_manager', 'secure_scan_create', 'threat_operate', 'VulManager', 'csovapp', 'project_schedule', 'SecurePenetrate', 'ISrc', 'project_list', 'outsourcing_user_manager', 'emergency_list', 'emergency_review'],
        'role': ['项目经理', '运营专家', '情报专家', '外包管理人', '销售', '管理员', '工程师']
    },
    'message': '成功!'
};

export const menutree = {
    'code': 200,
    'data': [{
        'id': 1,
        'name': '工作台',
        'type': 1,
        'parentId': 0,
        'permissionUri': '/',
        'children': [{
            'id': 52,
            'name': '情报热点',
            'type': 1,
            'parentId': 1,
            'permissionUri': '/desktop-intelligence'
        }, {
            'id': 53,
            'name': 'Dashboad',
            'type': 1,
            'parentId': 1,
            'permissionUri': '/dashboad'
        }]
    }, {
        'id': 2,
        'name': '项目管理',
        'type': 1,
        'parentId': 0,
        'permissionUri': '/project',
        'children': [{
            'id': 44,
            'name': '项目工作量列表',
            'type': 1,
            'parentId': 2,
            'permissionUri': '/project/workload'
        }, {
            'id': 62,
            'name': '项目列表',
            'type': 1,
            'parentId': 2,
            'permissionUri': '/project/list'
        }]
    }, {
        'id': 5,
        'name': '系统管理',
        'type': 1,
        'parentId': 0,
        'permissionUri': '/system',
        'children': [{
            'id': 13,
            'name': '系统用户管理',
            'type': 1,
            'parentId': 5,
            'permissionUri': '/system/staff'
        }, {
            'id': 14,
            'name': '角色管理',
            'type': 1,
            'parentId': 5,
            'permissionUri': '/system/roles'
        }, {
            'id': 15,
            'name': '扫描器管理',
            'type': 1,
            'parentId': 5,
            'permissionUri': '/permission/ScanManagement'
        }]
    }, {
        'id': 6,
        'name': '渗透测试',
        'type': 1,
        'parentId': 0,
        'permissionUri': '/penetration',
        'children': [{
            'id': 78,
            'name': '渗透报告列表',
            'type': 1,
            'parentId': 6,
            'permissionUri': '/penetration/list'
        }, {
            'id': 79,
            'name': '渗透新建报告',
            'type': 1,
            'parentId': 6,
            'permissionUri': '/penetration/add'
        }]
    }, {
        'id': 7,
        'name': '漏洞扫描',
        'type': 1,
        'parentId': 0,
        'permissionUri': '/scan',
        'children': [{
            'id': 80,
            'name': '漏扫报告列表',
            'type': 1,
            'parentId': 7,
            'permissionUri': '/scan/list'
        }, {
            'id': 81,
            'name': '漏扫新建报告',
            'type': 1,
            'parentId': 7,
            'permissionUri': '/scan/add'
        }]
    }, {
        'id': 8,
        'name': '配置检查',
        'type': 1,
        'parentId': 0,
        'permissionUri': '/checkconfig',
        'children': [{
            'id': 83,
            'name': '配置检查报告列表',
            'type': 1,
            'parentId': 8,
            'permissionUri': '/checkconfig/list'
        }]
    }, {
        'id': 16,
        'name': '漏洞管理',
        'type': 1,
        'parentId': 0,
        'permissionUri': '/vulmanager',
        'children': [{
            'id': 17,
            'name': '运维响应',
            'type': 1,
            'parentId': 16,
            'permissionUri': '/vulmanager/list',
            'children': [{
                'id': 87,
                'name': '运维响应项目经理',
                'type': 1,
                'parentId': 17,
                'permissionUri': '/vulmanager/list/project'
            }, {
                'id': 88,
                'name': '运维影响工程师',
                'type': 1,
                'parentId': 17,
                'permissionUri': '/vulmanager/list/engineer'
            }]
        }]
    }, {
        'id': 20,
        'name': '众测',
        'type': 1,
        'parentId': 0,
        'permissionUri': '/isrc',
        'children': [{
            'id': 90,
            'name': '众测列表',
            'type': 1,
            'parentId': 20,
            'permissionUri': '/isrc/list'
        }]
    }, {
        'id': 21,
        'name': '代码审计',
        'type': 1,
        'parentId': 0,
        'permissionUri': '/codeaudit',
        'children': [{
            'id': 84,
            'name': '代码审计列表',
            'type': 1,
            'parentId': 21,
            'permissionUri': '/codeaudit/list'
        }]
    }, {
        'id': 37,
        'name': '情报管理',
        'type': 1,
        'parentId': 0,
        'permissionUri': '/intelligence',
        'children': [{
            'id': 55,
            'name': '我的列表',
            'type': 1,
            'parentId': 37,
            'permissionUri': '/intelligence/list'
        }, {
            'id': 56,
            'name': '情报审核-情报专家',
            'type': 1,
            'parentId': 37,
            'permissionUri': '/intelligence/approved-1th'
        }, {
            'id': 57,
            'name': '情报审核-运营专家',
            'type': 1,
            'parentId': 37,
            'permissionUri': '/intelligence/approved-2th'
        }, {
            'id': 58,
            'name': '情报列表',
            'type': 1,
            'parentId': 37,
            'permissionUri': '/intelligence/threat'
        }, {
            'id': 59,
            'name': '恶意ip列表',
            'type': 1,
            'parentId': 37,
            'permissionUri': '/intelligence/maliciousip'
        }, {
            'id': 60,
            'name': '标签管理',
            'type': 1,
            'parentId': 37,
            'permissionUri': '/intelligence/incidenttags'
        }]
    }, {
        'id': 38,
        'name': '分析管理',
        'type': 1,
        'parentId': 0,
        'permissionUri': '/analysis',
        'children': [{
            'id': 63,
            'name': '告警分析',
            'type': 1,
            'parentId': 38,
            'permissionUri': '/analysis/warning'
        }, {
            'id': 64,
            'name': '日志分析',
            'type': 1,
            'parentId': 38,
            'permissionUri': '/analysis/log'
        }]
    }, {
        'id': 39,
        'name': '事件管理',
        'type': 1,
        'parentId': 0,
        'permissionUri': '/events',
        'children': [{
            'id': 65,
            'name': '事件研判',
            'type': 1,
            'parentId': 39,
            'permissionUri': '/events/research'
        }, {
            'id': 66,
            'name': '事件列表',
            'type': 1,
            'parentId': 39,
            'permissionUri': '/events/event'
        }]
    }, {
        'id': 40,
        'name': '应急响应',
        'type': 1,
        'parentId': 0,
        'permissionUri': '/incident',
        'children': [{
            'id': 67,
            'name': '应急列表',
            'type': 1,
            'parentId': 40,
            'permissionUri': '/incident/list',
            'children': [{
                'id': 68,
                'name': '应急列表项目经理',
                'type': 1,
                'parentId': 67,
                'permissionUri': '/incident/list/project'
            }, {
                'id': 69,
                'name': '应急列表工程师',
                'type': 1,
                'parentId': 67,
                'permissionUri': '/incident/list/engineer'
            }]
        }, {
            'id': 70,
            'name': '应急报告',
            'type': 1,
            'parentId': 40,
            'permissionUri': '/incident/reportList'
        }, {
            'id': 71,
            'name': '应急评审',
            'type': 1,
            'parentId': 40,
            'permissionUri': '/incident/examine'
        }, {
            'id': 72,
            'name': '应急同步',
            'type': 1,
            'parentId': 40,
            'permissionUri': '/incident/sync'
        }, {
            'id': 73,
            'name': '案例审核',
            'type': 1,
            'parentId': 40,
            'permissionUri': '/incident/managerCase'
        }, {
            'id': 74,
            'name': '应急案例',
            'type': 1,
            'parentId': 40,
            'permissionUri': '/incident/publiccase'
        }]
    }, {
        'id': 41,
        'name': '可视化展示样例',
        'type': 1,
        'parentId': 0,
        'permissionUri': '/demonstrate'
    }, {
        'id': 43,
        'name': '日程管理',
        'type': 1,
        'parentId': 0,
        'permissionUri': '/schedule',
        'children': [{
            'id': 75,
            'name': '项目排期',
            'type': 1,
            'parentId': 43,
            'permissionUri': '/schedule/list'
        }, {
            'id': 76,
            'name': '人员排期',
            'type': 1,
            'parentId': 43,
            'permissionUri': '/schedule/staff'
        }, {
            'id': 77,
            'name': '个人排期',
            'type': 1,
            'parentId': 43,
            'permissionUri': '/schedule/personal'
        }]
    }, {
        'id': 45,
        'name': '外包管理',
        'type': 1,
        'parentId': 0,
        'permissionUri': '/outsourc',
        'children': [{
            'id': 46,
            'name': '外包用户管理',
            'type': 1,
            'parentId': 45,
            'permissionUri': '/outsourc/outsourcsupplier'
        }, {
            'id': 47,
            'name': '外包工作量列表',
            'type': 1,
            'parentId': 45,
            'permissionUri': '/outsourc/workload'
        }]
    }, {
        'id': 48,
        'name': '简报管理',
        'type': 1,
        'parentId': 0,
        'permissionUri': '/hwdaily',
        'children': [{
            'id': 49,
            'name': '我的简报',
            'type': 1,
            'parentId': 48,
            'permissionUri': '/hwdaily/list'
        }, {
            'id': 50,
            'name': '项目简报',
            'type': 1,
            'parentId': 48,
            'permissionUri': '/hwdaily/product'
        }, {
            'id': 93,
            'name': '简报概况',
            'type': 1,
            'parentId': 48,
            'permissionUri': '/hwdaily/overview'
        }, {
            'id': 97,
            'name': '简报报表',
            'type': 1,
            'parentId': 48,
            'permissionUri': '/hwdaily/report'
        }]
    }, {
        'id': 51,
        'name': '销售情报管理',
        'type': 1,
        'parentId': 0,
        'permissionUri': '/salesIntelligence',
        'children': [{
            'id': 96,
            'name': '销售情报列表',
            'type': 1,
            'parentId': 51,
            'permissionUri': '/salesIntelligence/threat'
        }, {
            'id': 98,
            'name': '销售恶意ip列表',
            'type': 1,
            'parentId': 51,
            'permissionUri': '/salesIntelligence/maliciousip'
        }]
    }, {
        'id': 94,
        'name': '工作计划',
        'type': 1,
        'parentId': 0,
        'permissionUri': '/workplan',
        'children': [{
            'id': 95,
            'name': '工作计划列表',
            'type': 1,
            'parentId': 94,
            'permissionUri': '/workplan/list'
        }]
    }, {
        'id': 99,
        'name': '应用',
        'type': 1,
        'parentId': 0,
        'permissionUri': '/csovapp',
        'children': [{
            'id': 100,
            'name': '运营地图',
            'type': 1,
            'parentId': 99,
            'permissionUri': '/csovapp/sitemap'
        }, {
            'id': 101,
            'name': '运营情报',
            'type': 1,
            'parentId': 99,
            'permissionUri': '/csovapp/intelligence'
        }]
    }, {
        'id': 102,
        'name': '我的应用',
        'type': 1,
        'parentId': 0,
        'permissionUri': '/csovself',
        'children': [{
            'id': 103,
            'name': '云服务',
            'type': 1,
            'parentId': 102,
            'permissionUri': '/csovself/cloud'
        }, {
            'id': 104,
            'name': '专业服务',
            'type': 1,
            'parentId': 102,
            'permissionUri': '/csovself/professional',
            'children': [{
                'id': 105,
                'name': '漏洞管理',
                'type': 1,
                'parentId': 104,
                'permissionUri': '/csovself/professional/vul'
            }]
        }, {
            'id': 106,
            'name': '运营服务',
            'type': 1,
            'parentId': 102,
            'permissionUri': '/csovself/operation'
        }, {
            'id': 107,
            'name': '设备服务',
            'type': 1,
            'parentId': 102,
            'permissionUri': '/csovself/equipment'
        }, {
            'id': 108,
            'name': '资源服务',
            'type': 1,
            'parentId': 102,
            'permissionUri': '/csovself/resources'
        }, {
            'id': 109,
            'name': '智能服务',
            'type': 1,
            'parentId': 102,
            'permissionUri': '/csovself/intelligent'
        }, {
            'id': 110,
            'name': '场景服务',
            'type': 1,
            'parentId': 102,
            'permissionUri': '/csovself/hw',
            'children': [{
                'id': 111,
                'name': '护网场景',
                'type': 1,
                'parentId': 110,
                'permissionUri': '/csovself/hw/before'
            }]
        }, {
            'id': 112,
            'name': 'App服务',
            'type': 1,
            'parentId': 102,
            'permissionUri': '/csovself/app'
        }]
    }, {
        'id': 113,
        'name': '免费试用',
        'type': 1,
        'parentId': 0,
        'permissionUri': '/csovsTrial',
        'children': [{
            'id': 114,
            'name': '免费试用',
            'type': 1,
            'parentId': 113,
            'permissionUri': '/csovsTrial/free'
        }]
    }],
    'message': '成功!'
};
/* eslint-enable */
