import { TYPE_INPUT } from '@components/FormItem/utils';

export const basicFormconfig = [
    {
        type: TYPE_INPUT,
        name: 'keyword',
        label: '事件关键字',
        placeholder: '',
        options: [],
        rules: [],
        labelCol: {},
        wrapperCol: {},
    },
    {
        type: TYPE_INPUT,
        name: 'type',
        label: '事件类型',
        placeholder: '',
        options: [],
        rules: [],
        labelCol: {},
        wrapperCol: {},
    },
    {
        type: TYPE_INPUT,
        name: 'emergencyName',
        label: '事件名称',
        placeholder: '',
        options: [],
        rules: [],
        labelCol: {},
        wrapperCol: {},
    },
    {
        type: TYPE_INPUT,
        name: 'level',
        label: '事件级别',
        placeholder: '',
        options: [],
        rules: [],
        labelCol: {},
        wrapperCol: {},
    },
    {
        type: TYPE_INPUT,
        name: 'urgency',
        label: '事件紧急度',
        placeholder: '',
        options: [],
        rules: [],
        labelCol: {},
        wrapperCol: {},
    },
    {
        type: TYPE_INPUT,
        name: 'description',
        label: '事件描述',
        placeholder: '',
        options: [],
        rules: [],
        labelCol: {},
        wrapperCol: {},
    },
    {
        type: TYPE_INPUT,
        name: 'targetIp',
        label: '来源IP',
        placeholder: '',
        options: [],
        rules: [],
        labelCol: {},
        wrapperCol: {},
    },
    {
        type: TYPE_INPUT,
        name: 'attack',
        label: '攻击来源',
        placeholder: '',
        options: [],
        rules: [],
        labelCol: {},
        wrapperCol: {},
    },
    {
        type: TYPE_INPUT,
        name: 'IntranetSystem',
        label: '攻击所属业务系统',
        placeholder: '',
        options: [],
        rules: [],
        labelCol: {},
        wrapperCol: {},
    },
    {
        type: TYPE_INPUT,
        name: 'aimIp',
        label: '目的IP',
        placeholder: '',
        options: [],
        rules: [],
        labelCol: {},
        wrapperCol: {},
    },
    // {
    //     type: TYPE_INPUT,
    //     name: 'ips',
    //     label: '目的来源',
    //     placeholder: '',
    //     options: [],
    //     rules: [],
    //     labelCol: {},
    //     wrapperCol: {},
    // },
    // {
    //     type: TYPE_INPUT,
    //     name: 'ips',
    //     label: '目的所属业务系统',
    //     placeholder: '',
    //     options: [],
    //     rules: [],
    //     labelCol: {},
    //     wrapperCol: {},
    // },
    {
        type: TYPE_INPUT,
        name: 'discoverTime',
        label: '事件发现时间',
        placeholder: '',
        options: [],
        rules: [],
        labelCol: {},
        wrapperCol: {},
    },
    {
        type: TYPE_INPUT,
        name: 'realDiscoverTime',
        label: '事件发生时间',
        placeholder: '',
        options: [],
        rules: [],
        labelCol: {},
        wrapperCol: {},
    },
];
